In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df = pd.read_csv('/Users/starsrain/2025_concord/yieldCurve_augmenting/raw_data/1028_uwbV0.csv')

In [3]:
print("shape:", df.shape)
print("columns:", list(df.columns))
print("\nDtypes:\n", df.dtypes)
print("\nHead:")
display(df.head(5))
print("\nNulls (top 10):")
display(df.isna().sum().sort_values(ascending=False).head(10))

shape: (66441, 29)
columns: ['Application_ID', 'ApplicationDate', 'PortFolioID', 'LoanID', 'Frequency', 'LPCampaign', 'OriginatedAmount', 'OrigYear', 'OrigMonth', 'OrigWeek', 'OriginationDate', 'FPDFA', 'FPDAA', 'TotalRealizedPayin', 'InstallmentNumber', 'PaidOffPaymentAmount', 'DueDate', 'TransactionDate', 'PmtYear', 'PmtMonth', 'Days_Since_Orig', 'Weeks_Since_Orig', 'PaymentType', 'Payment_Number', 'PaymentStatus', 'weeks_between_orig_now', 'CustType', 'ProductType', 'PlanTypeName']

Dtypes:
 Application_ID              int64
ApplicationDate            object
PortFolioID                 int64
LoanID                     object
Frequency                  object
LPCampaign                 object
OriginatedAmount          float64
OrigYear                  float64
OrigMonth                 float64
OrigWeek                  float64
OriginationDate            object
FPDFA                     float64
FPDAA                     float64
TotalRealizedPayin        float64
InstallmentNumber           int64
PaidOffPaymentAmount      float64
DueDate                    object
TransactionDate            object
PmtYear                   float64
PmtMonth                  float64
Days_Since_Orig           float64
Weeks_Since_Orig          float64
PaymentType                object
Payment_Number              int64
PaymentStatus              object
weeks_between_orig_now    float64
CustType                   object
ProductType                object
PlanTypeName               object
dtype: object

Head:

,Application_ID,ApplicationDate,PortFolioID,LoanID,Frequency,LPCampaign,OriginatedAmount,OrigYear,OrigMonth,OrigWeek,...,PmtMonth,Days_Since_Orig,Weeks_Since_Orig,PaymentType,Payment_Number,PaymentStatus,weeks_between_orig_now,CustType,ProductType,PlanTypeName
0,107430982,2025-01-01 05:44:03.000,6,I2222175-0,B,RTRNGD,700.0,2025.0,1.0,1.0,...,1.0,2.0,1.0,Installment Pmt,1,D,43.0,RTG,I,Notazo default
1,107430982,2025-01-01 05:44:03.000,6,I2222175-0,B,RTRNGD,700.0,2025.0,1.0,1.0,...,1.0,15.0,3.0,Installment Pmt,2,D,43.0,RTG,I,Notazo default
2,107430982,2025-01-01 05:44:03.000,6,I2222175-0,B,RTRNGD,700.0,2025.0,1.0,1.0,...,1.0,29.0,5.0,Installment Pmt,3,D,43.0,RTG,I,Notazo default
3,107430982,2025-01-01 05:44:03.000,6,I2222175-0,B,RTRNGD,700.0,2025.0,1.0,1.0,...,2.0,43.0,7.0,Installment Pmt,4,D,43.0,RTG,I,Notazo default
4,107430982,2025-01-01 05:44:03.000,6,I2222175-0,B,RTRNGD,700.0,2025.0,1.0,1.0,...,2.0,58.0,9.0,Installment Pmt,5,D,43.0,RTG,I,Notazo default

Nulls (top 10):

FPDFA                     1790
DueDate                   1327
FPDAA                      127
TotalRealizedPayin          17
Weeks_Since_Orig             5
Days_Since_Orig              5
OriginationDate              4
weeks_between_orig_now       4
OrigYear                     4
OrigMonth                    4
dtype: int64

In [4]:
df['PlanTypeName'].value_counts()

PlanTypeName
Notazo default                41251
Flat Biweekly/Semi Monthly    15980
Flat Weekly LP                 5333
Arrangements                   2357
Flat Monthly LP                1520
Name: count, dtype: int64

In [5]:
df_noR = pd.read_csv('/Users/starsrain/2025_concord/yieldCurve_augmenting/raw_data/1028_uwb_noR.csv')

In [6]:
print("shape:", df_noR.shape)
print("columns:", list(df_noR.columns))
print("\nDtypes:\n", df_noR.dtypes)
print("\nHead:")
display(df_noR.head(5))

shape: (39628, 29)
columns: ['Application_ID', 'ApplicationDate', 'PortFolioID', 'LoanID', 'Frequency', 'LPCampaign', 'OriginatedAmount', 'OrigYear', 'OrigMonth', 'OrigWeek', 'OriginationDate', 'FPDFA', 'FPDAA', 'TotalRealizedPayin', 'InstallmentNumber', 'PaidOffPaymentAmount', 'DueDate', 'TransactionDate', 'PmtYear', 'PmtMonth', 'Days_Since_Orig', 'Weeks_Since_Orig', 'PaymentType', 'Payment_Number', 'PaymentStatus', 'weeks_between_orig_now', 'CustType', 'ProductType', 'PlanTypeName']

Dtypes:
 Application_ID              int64
ApplicationDate            object
PortFolioID                 int64
LoanID                     object
Frequency                  object
LPCampaign                 object
OriginatedAmount          float64
OrigYear                  float64
OrigMonth                 float64
OrigWeek                  float64
OriginationDate            object
FPDFA                     float64
FPDAA                     float64
TotalRealizedPayin        float64
InstallmentNumber           int64
PaidOffPaymentAmount      float64
DueDate                    object
TransactionDate            object
PmtYear                     int64
PmtMonth                    int64
Days_Since_Orig           float64
Weeks_Since_Orig          float64
PaymentType                object
Payment_Number              int64
PaymentStatus              object
weeks_between_orig_now    float64
CustType                   object
ProductType                object
PlanTypeName               object
dtype: object

Head:

,Application_ID,ApplicationDate,PortFolioID,LoanID,Frequency,LPCampaign,OriginatedAmount,OrigYear,OrigMonth,OrigWeek,...,PmtMonth,Days_Since_Orig,Weeks_Since_Orig,PaymentType,Payment_Number,PaymentStatus,weeks_between_orig_now,CustType,ProductType,PlanTypeName
0,107430982,2025-01-01 05:44:03.000,6,I2222175-0,B,RTRNGD,700.0,2025.0,1.0,1.0,...,1,2.0,1.0,Installment Pmt,1,D,43.0,RTG,I,Notazo default
1,107430982,2025-01-01 05:44:03.000,6,I2222175-0,B,RTRNGD,700.0,2025.0,1.0,1.0,...,1,15.0,3.0,Installment Pmt,2,D,43.0,RTG,I,Notazo default
2,107430982,2025-01-01 05:44:03.000,6,I2222175-0,B,RTRNGD,700.0,2025.0,1.0,1.0,...,1,29.0,5.0,Installment Pmt,3,D,43.0,RTG,I,Notazo default
3,107430982,2025-01-01 05:44:03.000,6,I2222175-0,B,RTRNGD,700.0,2025.0,1.0,1.0,...,2,43.0,7.0,Installment Pmt,4,D,43.0,RTG,I,Notazo default
4,107430982,2025-01-01 05:44:03.000,6,I2222175-0,B,RTRNGD,700.0,2025.0,1.0,1.0,...,2,58.0,9.0,Installment Pmt,5,D,43.0,RTG,I,Notazo default

In [7]:
df_noR['PlanTypeName'].value_counts()

PlanTypeName
Notazo default                25634
Flat Biweekly/Semi Monthly     8489
Flat Weekly LP                 3670
Flat Monthly LP                 942
Arrangements                    893
Name: count, dtype: int64